apiVersion: v1
kind: Secret
metadata:
  name: {{ template "taiga.fullname" . }}
  labels:
    app: {{ template "taiga.name" . }}
    chart: {{ template "taiga.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  taiga-secret-key: {{ .Values.taigaSecretKey | b64enc | quote }}
