apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-env-back
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  TAIGA_SECRET_KEY: {{ .Values.taiga.secretKey | b64enc | quote }}
  {{- if .Values.taiga.email.hostPassword }}
  EMAIL_HOST_PASSWORD: {{ .Values.taiga.email.hostPassword | b64enc | quote }}
  {{- end }}
  RABBITMQ_PASS: {{ .Values.rabbitmqasync.auth.password | b64enc | quote }}
  GITHUB_API_CLIENT_SECRET: {{ .Values.taiga.github.apiClientSecret | b64enc | quote }}
  GITLAB_API_CLIENT_SECRET: {{ .Values.taiga.gitlab.apiClientSecret | b64enc | quote }}
  GITHUB_IMPORTER_CLIENT_SECRET: {{ .Values.taiga.githubImporter.clientSecret | b64enc | quote }}
  JIRA_IMPORTER_CONSUMER_KEY: {{ .Values.taiga.jiraImporter.consumerKey | b64enc | quote }}
  TRELLO_IMPORTER_SECRET_KEY: {{ .Values.taiga.trelloImporter.secretKey | b64enc | quote }}
  CELERY_BROKER_URL: {{ include "taiga.celeryBrokerUrl" . | b64enc | quote }}
  EVENTS_PUSH_BACKEND_URL: {{ include "taiga.eventsPushBackendUrl" . | b64enc | quote }}
