apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-env-events
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
data:
  RABBITMQ_PASS: {{ .Values.rabbitmqevents.auth.password | b64enc | quote }}
  TAIGA_SECRET_KEY: {{ .Values.taiga.secretKey | b64enc | quote }}
