apiVersion: v1
kind: Service
metadata:
  name: taiga-front
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: taiga-front
      port: {{ .Values.taigaFront.port }}
      targetPort: http-front
  selector:
  {{- include "common.labels.matchLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: taiga-back
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: taiga-back
      port: {{ .Values.taigaBack.port }}
      targetPort: http-back
  selector:
  {{- include "common.labels.matchLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: taiga-protected
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: taiga-protected
      port: {{ .Values.taigaProtected.port }}
      targetPort: http-protected
  selector:
  {{- include "common.labels.matchLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: taiga-events
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: taiga-events
      port: {{ .Values.taigaEvents.port }}
      targetPort: ws-events
  selector:
  {{- include "common.labels.matchLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: taiga-async-rabbitmq
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: {{ .Values.rabbitmqasync.service.port }}
      targetPort: amqp
  selector:
    app.kubernetes.io/name: rabbitmqasync
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: taiga-events-rabbitmq
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
  {{- if .Values.commonAnnotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: {{ .Values.rabbitmqevents.service.port }}
      targetPort: amqp
  selector:
    app.kubernetes.io/name: rabbitmqevents
    app.kubernetes.io/instance: {{ .Release.Name }}
