{{- if and .Values.puppetdb.enabled .Values.puppetdb.puppetdbPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "puppetserver.fullname" . }}-puppetdb
  labels:
    app.kubernetes.io/name: {{ include "puppetserver.name" . }}-puppetdb
    helm.sh/chart: {{ include "puppetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  postgresql-password: {{ .Values.puppetdb.puppetdbPassword | b64enc | quote }}
{{- end -}}
