apiVersion: v1
kind: Service
metadata:
  name: {{ include "puppetserver.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "puppetserver.name" . }}
    helm.sh/chart: {{ include "puppetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "puppetserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
