{{- if .Values.puppetdb.enabled }}
{{- $this := . -}}
{{- range int .Values.puppetdb.replicaCount | until }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "puppetserver.fullname" $this }}-puppetdb-{{ . }}
  labels:
    app.kubernetes.io/name: {{ include "puppetserver.name" $this }}-puppetdb
    helm.sh/chart: {{ include "puppetserver.chart" $this }}
    app.kubernetes.io/instance: {{ $this.Release.Name }}
    app.kubernetes.io/managed-by: {{ $this.Release.Service }}
spec:
  type: {{ $this.Values.puppetdb.serviceType }}
  ports:
    - name: http
      port: {{ $this.Values.puppetdb.servicePortHttp }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ $this.Values.puppetdb.servicePortHttps }}
      targetPort: https
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "puppetserver.name" $this }}-puppetdb
    app.kubernetes.io/instance: {{ $this.Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ include "puppetserver.fullname" $this }}-puppetdb-{{ . }}
{{- end }}
{{- end }}

