{{- if .Values.ssh -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "puppetserver.fullname" . }}-ssh
  labels:
    app: {{ template "puppetserver.name" . }}
    chart: {{ template "puppetserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  config: {{ .Values.ssh.config | b64enc | quote }}
  id_rsa: {{ .Values.ssh.id_rsa | b64enc | quote }}
  id_rsa.pub: {{ .Values.ssh.id_rsa_pub | b64enc | quote }}
  known_hosts: {{ .Values.ssh.known_hosts | b64enc | quote }}
{{- end }}
