apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gradle-cache.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gradle-cache.name" . }}
    helm.sh/chart: {{ include "gradle-cache.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gradle-cache.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gradle-cache.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5071
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: gradle-cache-root
              subPath: logs
              mountPath: /data/logs
            - name: gradle-cache-root
              subPath: system
              mountPath: /data/system
            - name: gradle-configmap
              subPath: gradle-cache-config-yaml
              mountPath: /data/conf/config.yaml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: gradle-cache-root
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "gradle-cache.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: gradle-configmap
          configMap:
            name: {{ template "gradle-cache.fullname" . }}-configuration
