apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gerrit.fullname" . }}-plugins
  labels:
    app: {{ template "gerrit.name" . }}
    chart: {{ template "gerrit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  plugins: |
{{- range $key, $val := .Values.plugins }}
    {{ $key }}: {{ $val }}
{{- end}}
