apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gerrit.fullname" . }}
  labels:
    app: {{ template "gerrit.name" . }}
    chart: {{ template "gerrit.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end}}
