{{- if and .Values.rbac.create .Values.rbac.clusterRoleEnabled }}
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1beta1" }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- else if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1alpha1" }}
apiVersion: rbac.authorization.k8s.io/v1alpha1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
{{- end }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "jaeger-operator.fullname" . }}
  labels:
{{ include "jaeger-operator.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "jaeger-operator.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "jaeger-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
