apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "mailu.fullname" . }}-webmail
  labels:
    app.kubernetes.io/name: {{ include "mailu.name" . }}
    helm.sh/chart: {{ include "mailu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: webmail
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    {{/*nginx.nginx.ingress.kubernetes.io/configuration-snippet: |*/}}
      {{/*proxy_set_header Host $http_host;*/}}
      {{/*proxy_set_header X-Real-IP $remote_addr;*/}}
      {{/*proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;*/}}
      {{/*proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;*/}}
spec:
  tls:
  - hosts:
    - {{ .Values.mailu.hostname  }}
    secretName: {{ .Values.certificateSecretName }}
  rules:
  - host: {{ .Values.mailu.hostname  }}
    http:
      paths:
      - path: "/"
        backend:
          serviceName: webmail
          servicePort: http
