{{- if .Values.cache.s3.endpoint }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bazel-cache.fullname" . }}
  labels:
  {{- include "bazel-cache.labels" . | nindent 4 }}
type: Opaque
data:
  s3-access-key-id: {{ .Values.cache.s3.accessKeyId | b64enc | quote }}
  s3-secret-access-key: {{ .Values.cache.s3.secretAccessKey | b64enc | quote }}
{{- end }}