{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bazel-cache.serviceAccountName" . }}
  labels:
  {{- include "bazel-cache.labels" . | nindent 4 }}
{{- end -}}
