# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kibana:
  env:
    ELASTICSEARCH_URL: http://elasticsearch.namespace:9200
  ingress:
    enabled: false

fluentd-elasticsearch:
  elasticsearch:
    host: elasticsearch.namespace
    port: 9200
