# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kibana:
  env:
    ELASTICSEARCH_URL: http://elasticsearch.namespace:9200
  ingress:
    enabled: false

fluent-bit:
  backend:
    type: es
    es:
      host: elasticsearch.namespace
      port: 9200

elasticsearch-curator:
  config:
    elasticsearch:
      hosts:
        - elasticsearch.namespace
      port: 9200
