dependencies:
  - name: postgresql
    version: 9.1.1
    repository: https://charts.bitnami.com/bitnami
  - name: rabbitmq
    version: 7.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: taigaEventsEnabled
  - name: redis
    version: 10.7.11
    repository: https://charts.bitnami.com/bitnami
    condition: taigaEventsEnabled
