dependencies:
  - name: postgresql
    version: 3.10.1
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: rabbitmq
    version: 4.2.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: taigaEventsEnabled
  - name: redis
    version: 6.0.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: taigaEventsEnabled